/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.Color;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author dsola
 */
public class EditMatch extends javax.swing.JFrame {
  int stad;
  String Team;

       
    /**
     * Creates new form AddMatch
     */
    public EditMatch(String team) {
        this.Team=team;
        initComponents();
        fillListBoxStad();
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
     private void fillListBoxStad(){
    
    DefaultListModel m = new DefaultListModel();
               
    try{

           
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Project_db;user=sa;password=asdfghjkl12");
            String sql="Select * from Stadiums";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs1=pst.executeQuery();
            String Hello;
              while(rs1.next()){
                    Hello=rs1.getString("Name");
                     m.addElement(Hello);   
              }
                 StadiumList.setModel(m);
                 con.close();
        }        catch(Exception e){
                    System.out.println("error");
                    }

    }    
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base = new javax.swing.JPanel();
        Date_label = new javax.swing.JLabel();
        Stadium_label = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Update_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Day_field = new javax.swing.JTextField();
        Month_field = new javax.swing.JTextField();
        Year_field = new javax.swing.JTextField();
        Stadium_ScrollPane = new javax.swing.JScrollPane();
        StadiumList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Base.setBackground(new java.awt.Color(66, 77, 91));

        Date_label.setBackground(new java.awt.Color(54, 63, 75));
        Date_label.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Date_label.setText("Date :");

        Stadium_label.setBackground(new java.awt.Color(54, 63, 75));
        Stadium_label.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Stadium_label.setText("Stadium :");

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        Update_button.setBackground(new java.awt.Color(33, 40, 51));
        Update_button.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Update_button.setText("Update");
        Update_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Update_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Update_buttonMouseExited(evt);
            }
        });
        Update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("/");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("/");

        Day_field.setBackground(new java.awt.Color(33, 40, 51));
        Day_field.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Day_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Month_field.setBackground(new java.awt.Color(33, 40, 51));
        Month_field.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Month_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Year_field.setBackground(new java.awt.Color(33, 40, 51));
        Year_field.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Year_field.setForeground(new java.awt.Color(255, 255, 255));
        Year_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Year_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Year_fieldActionPerformed(evt);
            }
        });

        StadiumList.setBackground(new java.awt.Color(66, 77, 91));
        StadiumList.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        StadiumList.setForeground(new java.awt.Color(255, 255, 255));
        StadiumList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Stadium_ScrollPane.setViewportView(StadiumList);

        javax.swing.GroupLayout BaseLayout = new javax.swing.GroupLayout(Base);
        Base.setLayout(BaseLayout);
        BaseLayout.setHorizontalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaseLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BaseLayout.createSequentialGroup()
                        .addComponent(Date_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35))
                    .addGroup(BaseLayout.createSequentialGroup()
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BaseLayout.createSequentialGroup()
                                .addComponent(Day_field, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel1)
                                .addGap(1, 1, 1)
                                .addComponent(Month_field, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel2)
                                .addGap(1, 1, 1)
                                .addComponent(Year_field, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)))
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BaseLayout.createSequentialGroup()
                        .addComponent(Stadium_label, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addGap(122, 122, 122))
                    .addGroup(BaseLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Update_button)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BaseLayout.createSequentialGroup()
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Stadium_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        BaseLayout.setVerticalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaseLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stadium_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BaseLayout.createSequentialGroup()
                        .addComponent(Stadium_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Update_button)
                        .addGap(21, 21, 21))
                    .addGroup(BaseLayout.createSequentialGroup()
                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(Day_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Month_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Year_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(216, 237, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Year_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Year_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_fieldActionPerformed

    private void Update_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_buttonMouseEntered
       Update_button.setCursor(new Cursor(HAND_CURSOR));
       Update_button.setBackground(new Color(66,77,91));
       Update_button.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_Update_buttonMouseEntered

    private void Update_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_buttonMouseExited
       Update_button.setForeground(new Color(222,222,222));
       Update_button.setBackground(new Color(33,40,51));
    }//GEN-LAST:event_Update_buttonMouseExited

    private void Update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_buttonActionPerformed
String arr[] = Team.split(" ",2);
    try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Project_db;user=sa;password=asdfghjkl12");
            String sqlstad="Select * from Stadiums where Name=?";
            PreparedStatement pststad = con.prepareStatement(sqlstad);
            pststad.setString(1,StadiumList.getSelectedValue());
            ResultSet rsstad=pststad.executeQuery();
          
              while(rsstad.next()){
                    stad=rsstad.getInt("ID");
                
              }
            String sqlin="UPDATE Matches SET Date=?,Stadium_ID=? where Team_A=? and team_b=?;";
            PreparedStatement pstin = con.prepareStatement(sqlin);
            pstin.setString(1,Year_field.getText()+"-"+Month_field.getText()+"-"+Day_field.getText());
            pstin.setInt(2, stad);
             pstin.setString(3,arr[0].trim());
             pstin.setString(4,arr[1].trim());
            int rsin=pstin.executeUpdate();
    }catch(Exception e){
        System.out.println("Error Creating Match");
    }
    }//GEN-LAST:event_Update_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base;
    private javax.swing.JLabel Date_label;
    private javax.swing.JTextField Day_field;
    private javax.swing.JTextField Month_field;
    private javax.swing.JList<String> StadiumList;
    private javax.swing.JScrollPane Stadium_ScrollPane;
    private javax.swing.JLabel Stadium_label;
    private javax.swing.JButton Update_button;
    private javax.swing.JTextField Year_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
